07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at40
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - move(...) - Line#: 69 - DEBUG - inside the move() method. The path indexer is: 10
07/04/2016 10:20:35 PM - balloon.py - move(...) - Line#: 73 - DEBUG - just changed teh move() path_indexer value to 2. It is actually: 11
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - teleport(...) - Line#: 78 - DEBUG - inside teleport()
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - teleport(...) - Line#: 78 - DEBUG - inside teleport()
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - teleport(...) - Line#: 78 - DEBUG - inside teleport()
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - teleport(...) - Line#: 78 - DEBUG - inside teleport()
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 42 - CRITICAL - [<Mock spec='ExplosionBullet' id='82572624'>]
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 51 - DEBUG - =================== EXPLOSION BULLET=======================
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 54 - WARNING - inside the explosion bullet
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 42 - CRITICAL - [<Mock spec='StandardBullet' id='65387096'>]
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 46 - DEBUG - =================== STANDARD BULLET=======================
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 48 - WARNING - inside the standard bullet
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 42 - CRITICAL - [<Mock spec='TeleportationBullet' id='65384520'>]
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 57 - DEBUG - =================== TELEPORTATION BULLET=======================
07/04/2016 10:20:35 PM - balloon.py - teleport(...) - Line#: 78 - DEBUG - inside teleport()
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 42 - CRITICAL - [<Mock spec='int' id='82537608'>]
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - update(...) - Line#: 42 - CRITICAL - None
07/04/2016 10:20:35 PM - balloon.py - move(...) - Line#: 69 - DEBUG - inside the move() method. The path indexer is: 0
07/04/2016 10:20:35 PM - balloon.py - move(...) - Line#: 73 - DEBUG - just changed teh move() path_indexer value to 2. It is actually: 1
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - handle_pop(...) - Line#: 128 - DEBUG - inside BallonContext handle_pop()
07/04/2016 10:20:35 PM - balloon.py - handle_pop(...) - Line#: 130 - WARNING - 20
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - peel_layer(...) - Line#: 88 - DEBUG - inside BallonL1s peel_layer() method
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - peel_layer(...) - Line#: 94 - DEBUG - inside BallonL2s peel_layer() method
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - peel_layer(...) - Line#: 100 - DEBUG - inside BallonL3s peel_layer() method
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - peel_layer(...) - Line#: 106 - DEBUG - inside BallonL4s peel_layer() method
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - peel_layer(...) - Line#: 112 - DEBUG - inside BallonL5s peel_layer() method. The path index is: 0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
07/04/2016 10:20:35 PM - balloon.py - __init__(...) - Line#: 28 - DEBUG - PATH_INDEXER is at0
